# Backend Service (Django)
[service.backend]
path = "backend"
build = "pip install -r requirements.txt"
start = "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"

# Frontend Service (Next.js)
[service.frontend]
path = "frontend"
build = "npm install && npm run build"
start = "npm run start"

