import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import TestSidebar from "@/components/TestSidebar";
import HomeContent from "@/components/HomeContent";
import Tss from "./detail/[id]/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Booking clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger /> */}
        <TestSidebar mainContent={children} />
        {/* {children} */}
        {/* </main>
        </SidebarProvider> */}
      </body>
    </html>
  );
}
